services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4317
    networks:
      - app
      - elk

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    environment:
      - SERVER_URL=http://server:5000
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4317
    depends_on:
      - server
    networks:
      - app
      - elk

networks:
  app:
  elk:
    external: true
    name: elk
